### ISSUE TITLE
[Backend] Create the CompletedSurvey controller.

### ISSUE THREAD

**Issue by MichaelPatsula** [Christopher-Wang/StudyMonkey#24]
The Completed Survey controller shall do the following:
- be able to get a survey that a user filled out by providing the survey ID and the user ID as parameters. The response should be the survey details, all of its questions (including MC) and the user's answers to those questions.
- to be able to post all the answers to a particular user's survey

**Comment by ChristopheTran** [comment]
No longer relevant.
