### ISSUE TITLE
Weekly scrum - Week4 (Mar 26, 2021 - Apr 2, 2021)

### ISSUE THREAD

**Issue by Thomas-Leung** [Christopher-Wang/StudyMonkey#64]
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

**Comment by ChristopheTran** [comment]
- This week I added the feature to display metrics for text answers #67 
- I plan on working on any remaining issues. Possibly first working on answering MC. #52
- To work on answering MC questions, MC questions must be able to be created.

**Comment by RahulAnilkumar8** [comment]
- I added the splash screen for the application and fixed some tests and bugs in the survey viewing page. #63 
- I plan to work on the Range type survey question  answering  . #62 
- To work on the the answers, The range question creation must be implemented.

**Comment by Thomas-Leung** [comment]
- This week I fix the sign up page, rather than a JSON response return after sign up, it should return a webpage. https://github.com/Christopher-Wang/StudyMonkey/issues/55
- The coming week I will work on range question creation. https://github.com/Christopher-Wang/StudyMonkey/issues/61
- Nothing is blocked.

**Comment by MichaelPatsula** [comment]
- This week I worked off what @Christopher-Wang built previously to create the MC options #45. PR is open and awaiting approval. 
- This coming week I will be working on MC metrics. #58 
- Nothing is blocked

**Comment by Christopher-Wang** [comment]
- This week  I completed https://github.com/Christopher-Wang/StudyMonkey/issues/45. Pr is open and waiting approval
- This coming week I will be implementing range questions https://github.com/Christopher-Wang/StudyMonkey/issues/61
- Nothing is blocked
