### ISSUE TITLE
Weekly scrum - Week5 (Apr 2, 2021 - Apr 9, 2021)

### ISSUE THREAD

**Issue by Thomas-Leung** [Christopher-Wang/StudyMonkey#81]
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

**Comment by MichaelPatsula** [comment]
- This week I worked with @Christopher-Wang to develop the MC question metrics. #76 
- N/A
- N/A

**Comment by Thomas-Leung** [comment]
- This week I worked with @RahulAnilkumar8 for the range question https://github.com/Christopher-Wang/StudyMonkey/pull/72 and create metrics for range answer. https://github.com/Christopher-Wang/StudyMonkey/pull/75
- I will study for SYSC 4806 exam.
- Nothing is holding me back.

**Comment by RahulAnilkumar8** [comment]
- This week I completed the Splash screen and Range Question Creation and worked with Christophe and Chris on the session cookie implementation #63 #61 #78 
- N/A
- Nothing blocked me

**Comment by Christopher-Wang** [comment]
- This week I worked with @MichaelPatsula  to develop the MC question metrics. I also worked with @RahulAnilkumar8  and @ChristopheTran  to complete adding session cookies for user validation https://github.com/Christopher-Wang/StudyMonkey/issues/77
- N/A
- Nothing blocked me. Well done team

**Comment by ChristopheTran** [comment]
- This week I worked on answering MC questions #52 , answering range question #62, pair programmed session cookies with @Christopher-Wang  and @RahulAnilkumar8  #77, and modified logic answering and viewing answers when surveys are open or closed #79.  
- N/A
- Nothing blocked me.
